"""add-language-code-for-user

Revision ID: 544a963233cc
Revises: 2886627a096f
Create Date: 2024-02-26 12:06:07.350100

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "544a963233cc"
down_revision: Union[str, None] = "2886627a096f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("language_code", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language_code")
    # ### end Alembic commands ###
